version: '3'
services:
  catalog-service:
    build: ./catalog-service
    ports:
      - "8081:8080"

  cart-service:
    build: ./cart-service
    ports:
      - "8082:8080"

  inventory-service:
    build: ./inventory-service
    ports:
      - "8083:8080"
